# Use postgres/example user/password credentials
version: "3.1"

services:
  postgres-libreddit:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: jason # default 'postgres'
      POSTGRES_PASSWORD: secret
    volumes:
      - $HOME/docker/volumes/postgres/:/var/lib/postgresql/data/ # persist data
    networks:
      - postgres
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - postgres
    restart: unless-stopped
